name: Deploy Backend to Digital Ocean

on:
  push:
    branches:
      - main  # Triggers deployment when code is pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout Repository
      - name: Checkout Repo
        uses: actions/checkout@v3

      # ✅ Step 2: Set Up Environment Variables from GitHub Secrets
      - name: Set up environment variables
        run: |
          echo "MONGODB_URI=mongodb+srv://${{ secrets.MONGODB_USER }}:${{ secrets.MONGODB_PASSWORD }}@${{ secrets.MONGODB_CLUSTER }}/${{ secrets.MONGODB_DBNAME }}" >> $GITHUB_ENV
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL || 'default_frontend_url' }}" >> $GITHUB_ENV
          echo "PORT=8000" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "OPENAI_ASSISTANT_ID=${{ secrets.OPENAI_ASSISTANT_ID }}" >> $GITHUB_ENV

      # ✅ Step 3: Log in to DigitalOcean Container Registry (DOCR)
      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DOCR_USERNAME }}
          password: ${{ secrets.DOCR_ACCESS_TOKEN }}

      # ✅ Step 4: Build and Push Docker Image to DigitalOcean Container Registry
      - name: Build and Push Docker Image
        run: |
          docker build -t registry.digitalocean.com/${{ secrets.DOCR_REPOSITORY }}/resume-backend:latest .
          docker push registry.digitalocean.com/${{ secrets.DOCR_REPOSITORY }}/resume-backend:latest

      # ✅ Step 5: SSH into the DigitalOcean Droplet & Deploy
      - name: Deploy to Digital Ocean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull registry.digitalocean.com/${{ secrets.DOCR_REPOSITORY }}/resume-backend:latest
            docker stop resume-backend || true
            docker rm resume-backend || true
            docker run -d --name resume-backend -p 8000:8000 \
              -e MONGODB_URI=${{ secrets.MONGODB_URI }} \
              -e FRONTEND_URL=${{ secrets.FRONTEND_URL }} \
              -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
              -e OPENAI_ASSISTANT_ID=${{ secrets.OPENAI_ASSISTANT_ID }} \
              registry.digitalocean.com/${{ secrets.DROPLET_REPOSITORY }}/resume-backend:latest
